name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2 # Corrected the version to use v2
        with:
          node-version: 18.x
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: aws-actions/configure-aws-credentials@v1 # Updated the action to configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to AWS S3 or other service
        run: aws s3 cp . s3://your-bucket-name/ --recursive # Replace with your deployment command
