name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run Actions
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Set Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
          python --version
          echo 'PYTHON=python2.7' >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS
        uses: actions/aws/cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap_southeast_2
          aws-cli-version: 2.x
