name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install and Run Actions
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      name: Deploy to AWS
        uses: actions/aws-cli@v3
        with:
          aws-access-key-id: your-aws-access-key-id
          aws-secret-access-key: your-aws-secret-access-key
          region: us-east-1
