name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run Actions
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS
        uses: actions/aws/cli@v2
        with:
          aws-access-key-id: ${{ AKIAQMO6TRMYR362S2UO }}
          aws-secret-access-key: ${{ p9W54+erRFoxM+pyZ/lsEalSRHEjvJoW+r2YB3fd }}
          aws-region: us-east-1  # Change to your desired AWS region
          aws-cli-version: 2.x

